#
# SPDX-FileCopyrightText: Copyright (c) 2025 jrebuild project contributors as indicated by the @author tags
# SPDX-License-Identifier: Apache-2.0
#

version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "org.apache.maven.resolver:*"
        versions: [ ">=2.0.0" ]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
