#
# SPDX-FileCopyrightText: Copyright (c) 2025 jrebuild project contributors as indicated by the @author tags
# SPDX-License-Identifier: Apache-2.0
#

name: jrebuild
release:
  current-version: 
  next-version: 
