c#
# SPDX-FileCopyrightText: Copyright (c) 2025 jrebuild project contributors as indicated by the @author tags
# SPDX-License-Identifier: Apache-2.0
#

quarkus.banner.enabled = false
quarkus.log.min-level=TRACE

quarkus.log.category."org.l2x6.jrebuild".level=DEBUG
quarkus.log.category."org.l2x6.jrebuild.pnc".level=TRACE
quarkus.log.category."org.cliassured.CommandSpec".level=WARN

quarkus.index-dependency.pnc-rest-api.group-id=org.jboss.pnc

quarkus.rest-client.logging.scope=request-response
quarkus.rest-client.logging.body-limit=50
