#
# SPDX-FileCopyrightText: Copyright (c) 2025 jrebuild project contributors as indicated by the @author tags
# SPDX-License-Identifier: Apache-2.0
#

name: Linux & Windows CI

on:
  push:
    paths-ignore:
       - '.github/project.yml'

  pull_request:
    paths-ignore:
       - '.github/project.yml'

jobs:

  linux:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        java: [ 21 ]

    steps:

    - uses: actions/checkout@v5

    - uses: actions/setup-java@v5
      with:
        distribution: temurin
        java-version: ${{ matrix.java }}

    - name: mvn clean verify
      run: ./mvnw clean verify -B -ntp

  windows:

    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        java: [ 21 ]

    steps:

    - uses: actions/checkout@v5

    - uses: actions/setup-java@v5
      with:
        distribution: temurin
        java-version: ${{ matrix.java }}

    - name: mvn clean verify
      run: ./mvnw clean verify -B -ntp
